---
abstract: 'Read PDLs from NDF files and write PDLs to NDF files'
author:
  - 'Tim Jenness <tjenness@cpan.org>'
  - 'Douglas Burke <dburke@cfa.harvard.edu>'
build_requires:
  Test::More: 0
  Test::Number::Delta: 0
configure_requires:
  Module::Build: 0.3
dynamic_config: 1
generated_by: 'Module::Build version 0.4001, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: PDL-IO-NDF
requires:
  Astro::FITS::Header: 3
  NDF: 1.51
  PDL: v2.4.0
resources:
  homepage: http://github.com/timj/perl-PDL-IO-NDF/tree/master
  license: http://dev.perl.org/licenses/
  repository: git://github.com/timj/perl-PDL-IO-NDF.git
version: 1.04
